version: '3'

## Summary

# network:
#   app on port 8011
#   phpmyadmin on port 8012
#   mysql on port 8013

# auth:
# mysql:
#   user: root
#   pw: fkd91ok3fngncx

services:
  sid_app:
    container_name: sid_app
    build: .
    depends_on:
      - sid_mysql
    volumes:
      - ./index.php:/app/index.php
      - ./system:/app/system
      - ./assets:/app/assets
      - ./vendor:/app/vendor
      - ./desa:/app/desa
      - ./securimage:/app/securimage
      - ./themes:/app/themes
      - ./donjo-app/cache:/app/donjo-app/cache
      - ./donjo-app/config:/app/donjo-app/config
      - ./donjo-app/controllers:/app/donjo-app/controllers
      - ./donjo-app/core:/app/donjo-app/core
      - ./donjo-app/helpers:/app/donjo-app/helpers
      - ./donjo-app/hooks:/app/donjo-app/hooks
      - ./donjo-app/index.html:/app/donjo-app/index.html
      - ./donjo-app/language:/app/donjo-app/language
      - ./donjo-app/libraries:/app/donjo-app/libraries
      - ./donjo-app/logs:/app/donjo-app/logs
      - ./donjo-app/migrations:/app/donjo-app/migrations
      - ./donjo-app/models:/app/donjo-app/models
      - ./donjo-app/third_party:/app/donjo-app/third_party
      - ./donjo-app/views:/app/donjo-app/views
      
    environment:
      PHP_POOL_FILE: ./sid_app/pool.d/20-system.pool.conf
  sid_nginx:
    container_name: sid_nginx
    image: nginx:latest
    expose:
      - 80
    ports:
      - '8011:80'
    volumes:
      - ./sid_nginx/conf.d/sid.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    links:
      - sid_app
  sid_mysql:
    container_name: sid_mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: fkd91ok3fngncx
      MYSQL_DATABASE: sid
      TZ: 'Asia/Jakarta'
    volumes:
      - ./sid_mysql/initdb:/docker-entrypoint-initdb.d
      - sid_persistent:/var/lib/mysql
    ports:
      - '8013:3306'
  sid_phpmyadmin:
    container_name: sid_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: sid_mysql
    depends_on:
      - sid_mysql
    ports:
      - '8012:80'
volumes:
  sid_persistent:
